feat(tracing): Add initial support for Jaeger
gravitee-io/gravitee-tracer-jaeger pull request #1
Opened 2021-07-26 13:45 UTC by brasseld

Closes gravitee-io/issues#1581

2021-07-28 11:15 UTC, phiz71 approved these changes

2021-07-28 11:16 UTC, phiz71 requested changes
All is OK, but a README is missing.

2021-07-30 14:28 UTC, gaetanmaisse commented
@phiz71 the documentation looks ok  ✅

2021-07-30 14:39 UTC, phiz71 approved these changes

2021-08-02 06:18 UTC, merged