chore: Support for Java 17
gravitee-io/gravitee-tracer-jaeger pull request #9
Opened 2021-12-14 06:51 UTC by brasseld

Closes gravitee-io/issues#6708

2021-12-14 12:32 UTC, jhaeyaert approved these changes

2022-01-14 07:50 UTC, phiz71 requested changes

2022-01-14 07:50 UTC, phiz71 commented on pom.xml
> +        <gravitee-bom.version>1.5-SNAPSHOT</gravitee-bom.version>
should it be  2.0 instead ?

2022-01-14 07:50 UTC, phiz71 commented on pom.xml
> +        <gravitee-node-api.version>1.19.0-SNAPSHOT</gravitee-node-api.version>
should it be 1.20.0-SNAPSHOT ?

2022-01-24 12:48 UTC, phiz71 approved these changes

2022-01-24 13:08 UTC, merged